all:
	"C:\Program Files\CodeBlocks\MinGW\bin\g++.exe" -Wall -Wextra -O -ansi -pedantic -shared et1255.cpp -o libet1255.so -lsetupapi
	"C:\Program Files\CodeBlocks\MinGW\bin\g++.exe" -c et1255_dll_test.cpp
	"C:\Program Files\CodeBlocks\MinGW\bin\g++.exe" -o et1255_dll_test.exe et1255_dll_test.o libet1255.so